config/routes.rb
Rails.application.routes.draw do
  get 'comment/create'

  get 'comment/destroy'

  resources :prefereces
  get 'welcome/homepage'
  post 'welcome/places'
  get 'posts/index'
  devise_for :users, controllers: {
  	  sessions: "users/sessions",
  	registrations: 'users/registrations',
  	omniauth_callbacks: "users/omniauth_callbacks"

  }
  
  resources :posts do 
    resources :comments
  end
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

root 'welcome#homepage'
end

app/models/preferece.rb
class Preferece < ApplicationRecord
  belongs_to :search
  reverse_geocoded_by :latitude, :longitude
  after_validation :reverse_geocode
end

app/controllers/prefereces_controller.rb
class PreferecesController < ApplicationController
  before_action :set_preferece, only: [:show, :edit, :update, :destroy]
  attr_accessor :only

  # GET /prefereces
  # GET /prefereces.json
  def index
    @prefereces = Preferece.all
  end

  # GET /prefereces/1
  # GET /prefereces/1.json
  def show
  end

  # GET /prefereces/new
  def new
    @preferece = Preferece.new
  end

  # GET /prefereces/1/edit
  def edit
  end

  # POST /prefereces
  # POST /prefereces.json
  def create
    @preferece = Preferece.new(preferece_params)

    respond_to do |format|
      if @preferece.save
        format.html { redirect_to @preferece, notice: 'Preferece was successfully created.' }
        format.json { render :show, status: :created, location: @preferece }
      else
        format.html { render :new }
        format.json { render json: @preferece.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /prefereces/1
  # PATCH/PUT /prefereces/1.json
  def update
    respond_to do |format|
      if @preferece.update(preferece_params)
        format.html { redirect_to @preferece, notice: 'Preferece was successfully updated.' }
        format.json { render :show, status: :ok, location: @preferece }
      else
        format.html { render :edit }
        format.json { render json: @preferece.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /prefereces/1
  # DELETE /prefereces/1.json
  def destroy
    @preferece.destroy
    respond_to do |format|
      format.html { redirect_to prefereces_url, notice: 'Preferece was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_preferece
      @preferece = Preferece.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def preferece_params
      params.require(:preferece).permit(:type, :name, :description, :latitude, :longitude, :zone, :imgurl, :search_id, :address)
    end


end

app/helpers/prefereces_helper.rb
module PreferecesHelper
end

app/views/prefereces/_form.html.erb
<%= form_with(model: preferece, local: true) do |form| %>
  <% if preferece.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(preferece.errors.count, "error") %> prohibited this preferece from being saved:</h2>

      <ul>
      <% preferece.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :type %>
    <%= form.text_field :type, id: :preferece_type %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :preferece_name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description, id: :preferece_description %>
  </div>

  <div class="field">
    <%= form.label :latitude %>
    <%= form.text_field :latitude, id: :preferece_latitude %>
  </div>

  <div class="field">
    <%= form.label :ongitude %>
    <%= form.text_field :longitude, id: :preferece_longitude %>
  </div>

  <div class="field">
    <%= form.label :zone %>
    <%= form.text_field :zone, id: :preferece_zone %>
  </div>

  <div class="field">
    <%= form.label :imgurl %>
    <%= form.text_field :imgurl, id: :preferece_imgurl %>
  </div>

  <div class="field">
    <%= form.label :search_id %>
    <%= form.text_field :search_id, id: :preferece_search_id %>
  </div>

 <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address, id: :preferece_address %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/prefereces/edit.html.erb
<h1>Editing Preferece</h1>

<%= render 'form', preferece: @preferece %>

<%= link_to 'Show', @preferece %> |
<%= link_to 'Back', prefereces_path %>

app/views/prefereces/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Prefereces</h1>

<table>
  <thead>
    <tr>
      <th>Type</th>
      <th>Name</th>
      <th>Description</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th>Zone</th>
      <th>Imgurl</th>
      <th>Search</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @prefereces.each do |preferece| %>
      <tr>
        <td><%= preferece.type %></td>
        <td><%= preferece.name %></td>
        <td><%= preferece.description %></td>
        <td><%= preferece.latitude %></td>
        <td><%= preferece.longitude %></td>
        <td><%= preferece.zone %></td>
        <td><%= preferece.imgurl %></td>
        <td><%= preferece.search %></td>
        <td><%= link_to 'Show', preferece %></td>
        <td><%= link_to 'Edit', edit_preferece_path(preferece) %></td>
        <td><%= link_to 'Destroy', preferece, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Preferece', new_preferece_path %>

app/views/prefereces/new.html.erb
<h1>New Preferece</h1>

<%= render 'form', preferece: @preferece %>

<%= link_to 'Back', prefereces_path %>

app/views/prefereces/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Type:</strong>
  <%= @preferece.type %>
</p>

<p>
  <strong>Name:</strong>
  <%= @preferece.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @preferece.description %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @preferece.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @preferece.longitude %>
</p>

<p>
  <strong>Zone:</strong>
  <%= @preferece.zone %>
</p>

<p>
  <strong>Imgurl:</strong>
  <%= @preferece.imgurl %>
</p>

<p>
  <strong>Search:</strong>
  <%= @preferece.search %>
</p>

<%= link_to 'Edit', edit_preferece_path(@preferece) %> |
<%= link_to 'Back', prefereces_path %>