config/routes.rb
Rails.application.routes.draw do
  get 'comment/create'

  get 'comment/destroy'

  resources :prefereces
  get 'welcome/homepage'
  post 'welcome/places'
  get 'posts/index'
  devise_for :users, controllers: {
  	  sessions: "users/sessions",
  	registrations: 'users/registrations',
  	omniauth_callbacks: "users/omniauth_callbacks"

  }
  
  resources :posts do 
    resources :comments
  end
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

root 'welcome#homepage'
end

app/views/shared/_footer.html.erb
<!-- Footer -->
<footer>
  <div class="container">
    <div class="row">
      <div class="col-md-4">
        <span class="copyright">Copyright &copy; Guided You 2017</span>
      </div>
      <div class="col-md-4">
        <ul class="list-inline social-buttons">
          <li class="list-inline-item">
            <a href="#">
              <i class="fa fa-twitter"></i>
            </a>
          </li>
          <li class="list-inline-item">
            <a href="#">
              <i class="fa fa-facebook"></i>
            </a>
          </li>
          <li class="list-inline-item">
            <a href="#">
              <i class="fa fa-linkedin"></i>
            </a>
          </li>
        </ul>
      </div>
      <div class="col-md-4">
        <ul class="list-inline quicklinks">
          <li class="list-inline-item">
            <a href="#">Privacy Policy</a>
          </li>
          <li class="list-inline-item">
            <a href="#">Terms of Use</a>
          </li>
        </ul>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_navbar.html.erb
 <!-- Navigation -->
 <nav class="navbar navbar-expand-lg navbar-dark fixed-top" id="mainNav">
  <div class="container">
    <a class="navbar-brand js-scroll-trigger" href="#page-top">Guided You!</a>
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      Menu
      <i class="fa fa-bars"></i>
    </button>
    <%= link_to (image_tag('gol1.png', class: 'img-logo img-responsive')), welcome_homepage_path %>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav text-uppercase ml-auto">
        <!-- <li class="nav-item">
          <a class="nav-link js-scroll-trigger" href="#services">Guided You!</a>
        </li> -->
        <li class="nav-item">
          <a class="nav-link js-scroll-trigger" href="#portfolio">Recommendations</a>
        </li>
        <li class="nav-item">
          <a class="nav-link js-scroll-trigger" href="#about">How to use</a>
        </li>
        <li class="nav-item">
          <a class="nav-link js-scroll-trigger" href="#team">About Our</a>
        </li>
        <li class="nav-item">
          <a class="nav-link js-scroll-trigger" href="#contact">Contact me</a>
        </li>
        <li class="nav-item">
          <a class="nav-link js-scroll-trigger" href=" <%= posts_index_path %>">Blog Guided You!</a>
        </li>
        <li class="nav-item">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
              <% if user_signed_in? %>
              
              <%= current_user.name %>
              <% else %>
              <strong>Entrar</strong>
              <% end %>
              <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <% if user_signed_in? %>
                <li><%= link_to "Listado de usuarios", user_path if current_user.admin? %> <i class="fa fa-user" aria-hidden="true"></i></a></li>
                <li><%= current_user.name unless current_user.name.nil?  %> <i class="fa fa-wrench" aria-hidden="true"></i></a></li>
                <li class="divider"></li>
                <li><a href="<%= destroy_user_session_path %>" data-method='delete'>Cerrar Sesión <i class="fa fa-power-off" aria-hidden="true"></i></a></li>
                <% else %>
                <li><a href="<%= new_user_session_path %>">Ingresar</a></li>
                <li><a href="<%= new_user_registration_path %>">Registrarse</a></li>
                <% end %>

              </li>
              <div>


                <p class="notice"><%= notice %></p>
                <p class="alert"><%= alert %></p>


                <script>
                  window.fbAsyncInit = function() {
                    FB.init({
                      appId      : '1268097126628719',
                      cookie     : true,
                      xfbml      : true,
                      version    : 'v2.10'
                    });

                    FB.AppEvents.logPageView();   

                  };

                  (function(d, s, id){
                   var js, fjs = d.getElementsByTagName(s)[0];
                   if (d.getElementById(id)) {return;}
                   js = d.createElement(s); js.id = id;
                   js.src = "https://connect.facebook.net/en_US/sdk.js";
                   fjs.parentNode.insertBefore(js, fjs);
                 }(document, 'script', 'facebook-jssdk'));
               </script>
             </li>
           </ul>
         </div>

       </li>

     </li>
   </ul>
 </div>
</div>
</nav>